env:
  browser: true
  es6: true
extends:
  - plugin:import/typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - import
  - '@typescript-eslint'
rules:
  no-irregular-whitespace: 'error'
  no-useless-escape: 'error'
  '@typescript-eslint/adjacent-overload-signatures': 'error'
  '@typescript-eslint/array-type': ['error', { default:"array-simple" }]
  '@typescript-eslint/ban-ts-comment': 'error'
  '@typescript-eslint/ban-types': 'error'
  '@typescript-eslint/consistent-type-definitions': 'error'
  '@typescript-eslint/member-ordering': 'warn'
  '@typescript-eslint/no-empty-interface': 'error'
  '@typescript-eslint/no-extra-non-null-assertion': 'error'
  '@typescript-eslint/no-floating-promises': ['error', { ignoreVoid: true }]
  '@typescript-eslint/no-for-in-array': 'error'
  '@typescript-eslint/no-misused-new': 'error'
  '@typescript-eslint/no-misused-promises': 'error'
  '@typescript-eslint/no-non-null-asserted-optional-chain': 'error'
  '@typescript-eslint/no-throw-literal': 'error'
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error'
  '@typescript-eslint/no-unnecessary-type-arguments': 'error'
  '@typescript-eslint/no-unnecessary-type-assertion': 'error'
  '@typescript-eslint/prefer-as-const': 'error'
  '@typescript-eslint/prefer-includes': 'error'
  '@typescript-eslint/no-extraneous-class': 'error'
  '@typescript-eslint/no-this-alias': 'error'
  '@typescript-eslint/prefer-nullish-coalescing': 'error'
  '@typescript-eslint/prefer-optional-chain': 'error'
  '@typescript-eslint/prefer-regexp-exec': 'error'
  '@typescript-eslint/prefer-string-starts-ends-with': 'error'
  '@typescript-eslint/promise-function-async': 'error'
  '@typescript-eslint/switch-exhaustiveness-check': 'error'
  '@typescript-eslint/restrict-plus-operands': 'error'

  import/no-cycle: 'error'
  import/no-useless-path-segments: 'error'
  import/no-unused-modules: 'error'